package com.oneslide.mybatis.mybatis.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Address.id
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Address.street
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Address.details
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    private String details;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Address.userid
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Address.id
     *
     * @return the value of Address.id
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Address.id
     *
     * @param id the value for Address.id
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Address.street
     *
     * @return the value of Address.street
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Address.street
     *
     * @param street the value for Address.street
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Address.details
     *
     * @return the value of Address.details
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Address.details
     *
     * @param details the value for Address.details
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Address.userid
     *
     * @return the value of Address.userid
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Address.userid
     *
     * @param userid the value for Address.userid
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}