package com.oneslide.mybatis.mybatis.mapper;

import com.oneslide.mybatis.mybatis.model.Address;
import com.oneslide.mybatis.mybatis.model.AddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    long countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int deleteByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    Address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int updateByExample(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Address
     *
     * @mbg.generated Tue Apr 21 14:04:39 CST 2020
     */
    int updateByPrimaryKey(Address record);
}